export const messageWelcome = [
    `Oh...how do you go here - glhf!`,
    `Oh...how do you go here. Everyone, look busy!`,
    `You just access it.Can I get a heal?`,
    `Oh...how do you go here, my party.`,
    `User access. You must construct additional pylons.`,
    `Ermagherd. User is here.`,
    `Welcome, User.Stay awhile and listen.`,
    `Welcome, User.We were expecting you (͡° ͜ʖ ͡°)`,
    `Welcome, User.We hope you brought pizza.`,
    `Welcome User.Leave your weapons by the door.`,
    `A wild User appeared.`,
    `Swoooosh.User just landed.`,
    `Brace yourselves.User just access our, aaaaaaaa.....`,
    `User just joined.Hide your bananas.`,
    `User just arrived.Seems OP - please nerf.`,
    `User just slid into the server.`,
    `A User has spawned in the server.`,
    `Big User showed up!`,
    `Where’s User ? In the server!`,
    `User hopped into the server.Kangaroo!!`,
    `User just showed up.Hold my beer.`,
    `Challenger approaching - User has appeared!`,
    `It's a bird! It's a plane! Nevermind, it's just User.`,
    `It's User! Praise the sun!`,
    `Never gonna give User up.Never gonna let User down.`,
    `Ha! User has joined! You activated my trap card!`,
    `Cheers, love! User's here!`,
    `Hey! Listen! User has joined!`,
    `We've been expecting you User`,
    `It's dangerous to go alone, take User!`,
    `User has joined the server! It's super effective!`,
    `Cheers, love! User is here!`,
    `User is here, as the prophecy foretold.`,
    `User has arrived.Party's over.`,
    `Ready player User`,
    `User is here to kick butt and chew bubblegum.And User is all out of gum.`,
    `Hello.Is it User you're looking for?`,
    `User has joined.Stay a while and listen!`,
    `Roses are red, violets are blue, User joined this server with you`,
    `Hi, good to see you.`,
    `Pay acc, burh...`,
    `Bruh, just kidding...`,
    "Wobbling to 299%",
    "Untap, Upkeep, Draw",
    "Traveling to Hanamura",
    "TIME'S UP - LET'S DO THIS!",
    "This loading is a line",
    "They see me loading, They waiting",
    "Start your engines",
    "Skipping cutscenes",
    "Shuffling the deck",
    "Reviving dead memes",
    "Returning the slab",
    "Recombobulating Discombobulators",
    "Now with scratch and sniff",
    "Now with 100% more Screenshare!",
    "Dropping in Pochinki",
    "Looking for the power button",
    "Look behind you",
    "Locating Wumpus",
    "Loading your digital hug",
    "Loading Simulation",
    "Jumping to hyperspace",
    "Is this thing on?",
    "Initiating launch sequence",
    "Initializing socialization",
    "If you are reading this, you can read",
    "I swear it's around here somewhere...",
    "I need healing",
    "How do i turn this thing on",
    "Loading machine broke",
    "Get ready for a surprise!",
    "Finishing this senta...",
    "Dusting the cobwebs",
    "Do you even notice these?",
    "Opening the loading bay doors",
    "Why are you here...bruh...",
    "Disconnecting from Reality",
    "Charging spirit bomb",
    "Charging Limit Break",
    "Calibrating flux capacitors",
    "Buckle up!",
    "Assembling Voltron",
    "Are we there yet?",
    "A brawl is surely brewing!",
    "LOADING 001: ARP 303 Saw",
    "*Elevator Music Plays*",
    "Researching cheat codes",
    "Wizard needs food badly",
    "Decrypting Engrams",
    "And now for something completely different",
    "Stopping to smell the flowers",
    "Achieving Nirvana",
    "Managing Inventory",
]